DELETE FROM C; DELETE FROM D; DELETE FROM G; DELETE FROM L; DELETE FROM R;
DELETE FROM T; DELETE FROM U; DELETE FROM V; DELETE FROM X;

DELETE FROM c_types; DELETE FROM d_types; DELETE FROM g_types; DELETE FROM l_types; 
DELETE FROM r_types; DELETE FROM t_types; DELETE FROM u_types; DELETE FROM v_types; 
DELETE FROM x_types; 

DELETE FROM c_spec; DELETE FROM r_spec;

DELETE FROM units;